"""Generate /srv/llm/etc/models.ini from models.toml."""

from pathlib import Path

from ..step import Step

MODELS_INI = Path("/srv/llm/etc/models.ini")

# Keys in 'extra' that map directly to models.ini keys (underscore → hyphen).
EXTRA_KEY_MAP = {
    "jinja": "jinja",
    "min_p": "min-p",
    "temp": "temp",
    "top_p": "top-p",
    "threads": "threads",
    "mlock": "mlock",
    "cpu_moe": "cpu-moe",
}


class RouterConfigStep(Step):
    name = "router-config"
    description = "Generate models.ini for llama-server router"

    def check(self) -> bool:
        # Regenerate every run so it stays in sync with models.toml.
        return False

    def run(self) -> None:
        d = self.config.defaults
        lines = [
            "# Auto-generated by inference installer — do not edit by hand.",
            "# Source of truth: models.toml",
            "",
            "version = 1",
            "",
            "[*]",
            f"mmap = {'true' if d.mmap else 'false'}",
            f"parallel = {d.parallel}",
            f"cache-type-k = {d.cache_type_k}",
            f"cache-type-v = {d.cache_type_v}",
            f"device = {d.device}",
            f"n-gpu-layers = {d.gpu_layers}",
            f"ctx-size = {d.ctx_size}",
            f"no-warmup = {'true' if d.no_warmup else 'false'}",
            "cache-ram = 0",
        ]

        for model in self.config.models:
            for profile in model.profiles:
                lines.append("")
                lines.append(f"[{profile.name}]")
                lines.append(f"model = {model.first_gguf}")

                if profile.ctx_size != d.ctx_size:
                    lines.append(f"ctx-size = {profile.ctx_size}")

                if str(profile.gpu_layers) != str(d.gpu_layers):
                    lines.append(f"n-gpu-layers = {profile.gpu_layers}")

                if profile.device is not None:
                    lines.append(f"device = {profile.device}")

                for key, ini_key in EXTRA_KEY_MAP.items():
                    if key in profile.extra:
                        val = profile.extra[key]
                        if isinstance(val, bool):
                            val = "true" if val else "false"
                        lines.append(f"{ini_key} = {val}")

                # Pass through any extra keys not in the map
                for key, val in profile.extra.items():
                    if key not in EXTRA_KEY_MAP:
                        ini_key = key.replace("_", "-")
                        if isinstance(val, bool):
                            val = "true" if val else "false"
                        lines.append(f"{ini_key} = {val}")

        lines.append("")  # trailing newline
        content = "\n".join(lines)

        MODELS_INI.parent.mkdir(parents=True, exist_ok=True)
        MODELS_INI.write_text(content)
        self.sh(f"chown llm:llm {MODELS_INI}")
        self.sh(f"chmod 0644 {MODELS_INI}")
        print(f"   Wrote {MODELS_INI} ({len(self.config.models)} models, "
              f"{sum(len(m.profiles) for m in self.config.models)} profiles)")
