"""Validate that the generated models.ini is well-formed."""

import argparse
import configparser
import re
import unittest


def _load():
    from installer.config import load_config
    ns = argparse.Namespace(
        models_toml=None, prune=False, dry_run=True, host="0.0.0.0", port=8000,
    )
    return load_config(ns)


def _generate_ini(config) -> str:
    """Generate ini content using the actual router_config step logic."""
    from installer.steps.router_config import RouterConfigStep
    from installer.hardware import Hardware

    step = RouterConfigStep(config, Hardware())
    # Reach into the step's run() logic without writing to disk.
    # Replicate only the string building part.
    from installer.steps.router_config import EXTRA_KEY_MAP

    d = config.defaults
    lines = [
        "# Auto-generated by inference installer",
        "",
        "version = 1",
        "",
        "[*]",
        f"mmap = {'true' if d.mmap else 'false'}",
        f"parallel = {d.parallel}",
        f"cache-type-k = {d.cache_type_k}",
        f"cache-type-v = {d.cache_type_v}",
        f"device = {d.device}",
        f"n-gpu-layers = {d.gpu_layers}",
        f"ctx-size = {d.ctx_size}",
        f"no-warmup = {'true' if d.no_warmup else 'false'}",
        "cache-ram = 0",
    ]

    for model in config.models:
        for profile in model.profiles:
            lines.append("")
            lines.append(f"[{profile.name}]")
            lines.append(f"model = {model.first_gguf}")
            if profile.ctx_size != d.ctx_size:
                lines.append(f"ctx-size = {profile.ctx_size}")
            if str(profile.gpu_layers) != str(d.gpu_layers):
                lines.append(f"n-gpu-layers = {profile.gpu_layers}")
            if profile.device is not None:
                lines.append(f"device = {profile.device}")
            for key, ini_key in EXTRA_KEY_MAP.items():
                if key in profile.extra:
                    val = profile.extra[key]
                    if isinstance(val, bool):
                        val = "true" if val else "false"
                    lines.append(f"{ini_key} = {val}")
            for key, val in profile.extra.items():
                if key not in EXTRA_KEY_MAP:
                    ini_key = key.replace("_", "-")
                    if isinstance(val, bool):
                        val = "true" if val else "false"
                    lines.append(f"{ini_key} = {val}")

    return "\n".join(lines) + "\n"


def _parse_ini(content: str) -> configparser.ConfigParser:
    """Parse llama.cpp models.ini, skipping the preamble before the first section."""
    # Strip lines before the first [section] — llama.cpp puts 'version = 1' there.
    lines = content.splitlines(keepends=True)
    start = 0
    for i, line in enumerate(lines):
        if line.strip().startswith("["):
            start = i
            break
    trimmed = "".join(lines[start:])
    parser = configparser.ConfigParser()
    parser.read_string(trimmed)
    return parser


class TestRouterConfig(unittest.TestCase):

    def test_ini_is_parseable(self):
        """The generated ini must parse without errors."""
        config = _load()
        ini_content = _generate_ini(config)
        parser = _parse_ini(ini_content)
        expected_profiles = sum(len(m.profiles) for m in config.models)
        non_default = [s for s in parser.sections() if s != "DEFAULT"]
        self.assertEqual(len(non_default), expected_profiles + 1)  # +1 for [*]

    def test_every_profile_has_model_path(self):
        config = _load()
        ini_content = _generate_ini(config)
        parser = _parse_ini(ini_content)
        for section in parser.sections():
            if section == "*":
                continue
            with self.subTest(section=section):
                self.assertTrue(
                    parser.has_option(section, "model"),
                    f"[{section}] missing 'model' key",
                )
                model_path = parser.get(section, "model")
                self.assertTrue(
                    model_path.startswith("/srv/llm/models/"),
                    f"[{section}] model path doesn't start with /srv/llm/models/: {model_path}",
                )

    def test_has_version_line(self):
        config = _load()
        ini_content = _generate_ini(config)
        self.assertIn("version = 1", ini_content)

    def test_no_duplicate_sections(self):
        """Profile names must not collide — configparser silently merges dupes."""
        config = _load()
        ini_content = _generate_ini(config)
        sections = []
        for line in ini_content.splitlines():
            stripped = line.strip()
            if stripped.startswith("[") and stripped.endswith("]"):
                sections.append(stripped[1:-1])
        self.assertEqual(len(sections), len(set(sections)), "Duplicate ini sections")


if __name__ == "__main__":
    unittest.main()
